### ISSUE TITLE
Clicking on 'Capture' opens a new activity, and pressing the back button opens the camera

### ISSUE THREAD

**Issue by nitinkgp23** [nitinkgp23/curread#4]
On clicking capture, camera should open, and after clicking the photo, new activity should open. The order in which these functions are called, is opposite.

**Comment by MansiThakkar** [comment]
It is working on my repo

**Comment by snufflesrea** [comment]
It is also working with my emulator
Only the dispatchTakePictureIntent() session is in a very short time, so all I can see is the main2activity.

**Comment by nitinkgp23** [comment]
Okay, maybe there is a problem in my case. Will have to look into it. You should go ahead with this then. @MansiThakkar @snufflesrea
